services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: syslog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:admin@postgres:5432/syslog
    depends_on:
      - postgres

