name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: syslog
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
        # Wait for the service to be ready
        options: --health-cmd="pg_isready -U postgres"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

    - name: Run Unit Tests
      run: |
        pytest tests/unit  # Assuming unit tests will be in 'tests/unit'

    - name: Run Integration Tests
      run: |
        pytest tests/integration  # Assuming integration tests will be in 'tests/integration'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up Docker Compose
      uses: docker/setup-buildx-action@v3

    - name: Build and run services
      run: docker-compose up -d --build

    - name: Run tests
      run: docker run --rm app pytest

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: |
        docker tag syslog_manager:latest ${{ secrets.DOCKER_USERNAME }}/syslog_manager:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/syslog_manager:latest
    
